# Generated by Django 5.1.6 on 2025-03-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hallticketNum', models.CharField(max_length=10)),
                ('phnNum', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('conPassword', models.CharField(max_length=10)),
            ],
        ),
    ]
