# Generated by Django 5.1.6 on 2025-04-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLogin', '0002_remove_studentreg_conpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreg',
            old_name='name',
            new_name='studentName',
        ),
        migrations.RemoveField(
            model_name='studentreg',
            name='hallticketNum',
        ),
        migrations.RemoveField(
            model_name='studentreg',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentreg',
            name='phnNum',
        ),
        migrations.AddField(
            model_name='studentreg',
            name='image',
            field=models.ImageField(default='studentImages/default.png', upload_to='studentImages/'),
        ),
        migrations.AddField(
            model_name='studentreg',
            name='phoneNum',
            field=models.CharField(default='null', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='studentreg',
            name='studentPassword',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='studentreg',
            name='hallTicketNum',
            field=models.CharField(default='null', max_length=20, unique=True),
        ),
    ]
