# Generated by Django 5.1.6 on 2025-05-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLogin', '0003_rename_name_studentreg_studentname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='hallTicketNum',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='image',
            field=models.ImageField(upload_to='studentImages/'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='phoneNum',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='studentPassword',
            field=models.CharField(max_length=20),
        ),
    ]
