# Generated by Django 5.1.6 on 2025-05-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultyReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=30)),
                ('facultyId', models.CharField(default='null', max_length=20, unique=True)),
                ('phoneNum', models.CharField(default='null', max_length=15, unique=True)),
                ('image', models.ImageField(default='facultyImages/default.png', upload_to='facultyImages/')),
                ('facultyPassword', models.CharField(default='null', max_length=10)),
            ],
        ),
    ]
